spring.application.name=RestaurantApp
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/restaurant
spring.datasource.username=restaurant
spring.datasource.password=restaurant_secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
